### ISSUE TITLE
Ping encoding

### ISSUE THREAD

**Issue by ZatsuneSakurako** [geminate/d-tools#2]
The ping tool does not show chars correctly with French language (the system defined language). Could it be fixed ? (it's on Windows 10 `Microsoft Windows [version 10.0.17134.254]`)

![image](https://user-images.githubusercontent.com/7016954/45264477-5b25aa80-b43d-11e8-81a7-5a9ffddcd335.png)

**Comment by geminate** [comment]
Fixed. 0.1.3
